# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys

bind -N "Lock server"                ^X lock-server

bind -N "New window in \$HOME"       ^C new-window -c "$HOME"
bind -N "Detach client"              ^D detach

bind -N "Previous window"            H previous-window
bind -N "Next window"                L next-window

bind -N "Rename window"              r command-prompt "rename-window %%"

bind -N "Reload tmux.conf"           R source-file ~/.config/tmux/tmux.conf

bind -N "Last window"                ^A last-window

bind -N "List windows"               ^W list-windows
bind -N "List windows"               w list-windows
bind -N "Toggle zoom"                z resize-pane -Z

bind -N "Refresh client"             ^L refresh-client
bind -N "Refresh client"             l refresh-client
bind -N "Split vertical"             | split-window
bind -N "Split vertical (cwd)"       s split-window -v -c "#{pane_current_path}"
bind -N "Split horizontal (cwd)"     v split-window -h -c "#{pane_current_path}"
bind -N "Choose window"              '"' choose-window

bind -N "Select pane left"           h select-pane -L
bind -N "Select pane down"           j select-pane -D
bind -N "Select pane up"             k select-pane -U
bind -N "Select pane right"          l select-pane -R
bind -N "Resize pane left"  -r -T prefix , resize-pane -L 20
bind -N "Resize pane right" -r -T prefix . resize-pane -R 20
bind -N "Resize pane down"  -r -T prefix - resize-pane -D 7
bind -N "Resize pane up"    -r -T prefix = resize-pane -U 7
bind -N "Command prompt"             : command-prompt
bind -N "Toggle pane sync"           * setw synchronize-panes
bind -N "Toggle pane border status"  P set pane-border-status
bind -N "Kill pane"                  c kill-pane

bind -N "Swap pane down"             x swap-pane -D
bind -N "Choose session"             S choose-session

bind -N "Reload tmux.conf"           R source-file ~/.config/tmux/tmux.conf
bind -N "Clear screen"               K send-keys "clear"\; send-keys "Enter"
bind-key -N "Begin selection" -T copy-mode-vi v send-keys -X begin-selection

bind -N "Nuke resurrect & quit" ^Q confirm-before -p "Clear resurrect data and quit tmux? (y/n)" \
  "run-shell 'rm -rf ~/.local/share/tmux/resurrect && mkdir -p ~/.local/share/tmux/resurrect && tmux kill-server'"
